name: Release 📦

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  release:
    uses: kolvin/workflows/.github/workflows/automated-semver.yaml@main
    secrets:
      BOT_GPG_PRIVATE_KEY: ${{ secrets.BOT_GPG_PRIVATE_KEY }}
      BOT_GPG_PASSPHRASE: ${{ secrets.BOT_GPG_PASSPHRASE }}
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

